config/routes.rb
Neu2::Application.routes.draw do
  resources :personal
  resources :customers
  resources :order
  resources :products
  resources :categories

  get "order/show_order/:id" => "order#show_order", as: :show_customer_order
  get "order/show"
  get "personal/index"
  get "personal/show"
  get "startseite/index"
  root to: "customers#index"
  resources :users

  devise_for :users, :path_prefix => 'my'

end

app/controllers/personal_controller.rb
class PersonalController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users=User.all
  end

  def show
  end

end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/views/personal/_navigationsbar.html.erb
    <nav class="navbar navbar-inverse" role="navigation">
        <ul class="nav navbar-nav navbar-left">

            <li>
                <%= image_tag "logo.png", :size => "70x50" %>
            </li>
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li>
                <%= link_to "Produkte", products_path %>
            </li>
            <li>
                <%= link_to "Kategorien", categories_path %>
            </li>
            <li>
                <%= link_to "Mitarbeiter", users_path %>
            </li>
            <li>
                <%= link_to "Bestellhistorie", order_show_path %>
            </li>
            <li>
                <%= link_to "FAQ", personal_show_path %>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

            <li>
                <% if user_signed_in? %>
                <%= link_to "Abmelden", destroy_user_session_path, :method => :delete %>
                <% end %></div>
            </li>
        </ul>
    </nav>

app/views/personal/index.html.erb
  <div class="col-md-15 drag-div">
    <div class="form-group">
      <div id="products">
        <h1 class="page-header"><tt>Mitarbeiter</tt></h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Email</th>
              <th>zuletzt angemeldet</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.email %></td>
              <td><%= user.last_sign_in_at %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <br>
      </div>
    </div>
    <%= link_to 'Neuer Mitarbeiter', :controller => 'devise/registrations', :action => 'new', :class => 'btn btn-info btn-xs' %>
  </div>

app/views/personal/show.html.erb
  <div class="col-md-15 drag-div">
    <div class="form-group">
      <div id="products">
        <h2 class="page-header">FAQ</h2>
        <p><i>Häufig gestellte Fragen finden Sie hier:</i> </p>
      </div>

      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                Wer darf Produkte, Kategorien und Mitarbeiter erstellen, löschen und ändern?       </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
              <div class="panel-body">
                Nur der Admin.        </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                   Wie hoch ist der Mindestbestellwert?
                 </a>
               </h4>
             </div>
             <div id="collapseTwo" class="panel-collapse collapse">
              <div class="panel-body">
               ab 7,00 € Adlershof, Altglienicke, Bohnsdorf, Grünau, westlich Dahme<br>
               ab 9,00 € Johannisthal, Niederschöneweide, Rudow<br>
               ab 15,00 € Flughafen Schönefeld, Schönefeld-Ort, Waltersdorf   </div>
             </div>
           </div>
           <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                  Wo werden unsere Getränke bestellt?
                </a>
              </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
              <div class="panel-body">
                "Ick koof bei Lehmann" <br>
                Oranienburger Str. 53 in 13437 Berlin<br>
                Tel. : +49 331 - 6697 - 0
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
                  Wo werden unsere Lebensmittel bestellt?
                </a>
              </h4>
            </div>
            <div id="collapse4" class="panel-collapse collapse">
              <div class="panel-body">
                Younes Service GmbH<br>
                Buckower Damm 34, 12349 Berlin<br>
                Tel.: 030/ 63 41 30 290<br>
                Fax: 030 / 63 41 30 29 49<br>
                E.Mail: info@younes-berlin.de<br>

              </div>
            </div>
          </div>


          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse5">
                  Wann gibt es einen Zuschlag für den Fahrer?   </a>
                </h4>
              </div>
              <div id="collapse5" class="panel-collapse collapse">
                <div class="panel-body">
                  Für alle Touren, die mehr als 4km entfernt sind,
                  erhält der Lieferant 2€ Zuschlag.
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>